version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: pokemon_container_client
    ports:
      - '3000:3000'
    volumes: 
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    build:
      context: ./api
    container_name: pokemon_container_api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: pokemon_container_db
    ports:
      - '3306:3306'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: pokemon
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pokemon_container_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data:
